### ISSUE TITLE
Add CORS in server js code

### ISSUE THREAD

**Issue by vaynetian** [jungkumseok/ubc-vsp18-server#1]
No cors or allow-origin options is set in index.js, so that problems like SEC7120 CORS will come out when uploading the server code on the remote server.

Recommand that add npm package 'cors' and ```app.use(cors());``` in index.js

**Comment by vaynetian** [comment]
ADD: Not only using remote server but local deploy will meet problems like above.

And PR is committed to solve this problem.

**Comment by jungkumseok** [comment]
Thanks!
